name: Deploy Website

on:
  workflow_run:
    workflows: ["Generate and Deploy Website"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: github-pages
          path: site_contents
          workflow: main.yml
          run_id: ${{ github.event.workflow_run.id }}

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_PAGES_TOKEN }}
          publish_dir: site_contents
